// 기본적인 웹페이지 골격을 설정하는 곳

import Link from 'next/link';
import './globals.css';
// -> 루트 레이아웃이라 global 파일을 불러오고 있음

export const metadata = {
  title: 'Web Tutorials',
  description: 'Generated by HJ.Cho',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          <li>
            <Link href="/read/1">HTML</Link>
          </li>
          <li>
            <Link href="/read/2">CSS</Link>
          </li>
        </ol>
        {/* children은 src/app/page.js에서 온다 */}
        {children}
        <ul>
          <li>
            <Link href="/create">CREATE</Link>
          </li>
          <li>
            <Link href="/update/1">UPDATE</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
