// 기본적인 웹페이지 골격을 설정하는 곳

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
      {/* children은 page.js에서 온다 */}
    </html>
  );
}
