// 기본적인 웹페이지 골격을 설정하는 곳

import './globals.css';

export const metadata = {
  title: 'Web Tutorials',
  description: 'Generated by HJ.Cho',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>
        </h1>
        <ol>
          <li>
            <a href="/read/1">HTML</a>
          </li>
          <li>
            <a href="/read/2">CSS</a>
          </li>
        </ol>
        {/* children은 src/app/page.js에서 온다 */}
        {children}
        <ul>
          <li>
            <a href="/create">CREATE</a>
          </li>
          <li>
            <a href="/update/1">UPDATE</a>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
