// root layout

import Navigation from './../components/navigation';

export const metadata = {
  title: 'Study Next.js with Nomadcoders',
  description: 'Generated by HJ Cho',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
