// root layout

export const metadata = {
  title: 'Study Next.js with Nomadcoders',
  description: 'Generated by HJ Cho',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
