// root layout

import { Metadata } from 'next';
import Navigation from './../components/navigation';
import '../styles/global.css';

export const metadata: Metadata = {
  title: {
    template: '%s | Study Next.js',
    default: 'Study Next.js',
  },
  description: 'Generated by HJ Cho',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
